import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BlurEffects from "../components/global/Blur-effects";
import Nav from "@/components/global/Nav";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await auth()

  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Nav user={user} />
        {children}
        <BlurEffects />
      </body>
    </html>
  );
}
